#!/usr/bin/env sh
#
# Generate one Traefik router per hostname.
#
#   sh deploy/gen-routers.sh > deploy/compose.routers.yml
#
# A single router matching several Host() rules makes the proxy request ONE
# certificate carrying every hostname in its SAN list — so each tenant's
# certificate names all the others, and so do the public Certificate
# Transparency logs. For demonstration pages sent to competing businesses that
# leaks the whole recipient list.
#
# One router per host means one certificate per host, and nothing to correlate.
# Hostnames come from DEMO_HOSTS in deploy/.env; no tenant is named here.
set -eu

HERE="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1091
. "$HERE/.env"

: "${DEMO_HOSTS:?set DEMO_HOSTS in deploy/.env (comma-separated hostnames)}"
: "${ACME_RESOLVER:?set ACME_RESOLVER in deploy/.env}"

printf '# GENERATED by gen-routers.sh — do not edit. Regenerate after changing DEMO_HOSTS.\n'
printf 'services:\n  app:\n    labels:\n'

echo "$DEMO_HOSTS" | tr ',' '\n' | while read -r host; do
  host="$(printf '%s' "$host" | tr -d '[:space:]')"
  [ -n "$host" ] || continue
  # Router name from the leftmost label, sanitised. Unique per host.
  name="demo-$(printf '%s' "$host" | cut -d. -f1 | tr -c 'a-zA-Z0-9-' '-')"
  printf '      traefik.http.routers.%s.rule: "Host(`%s`)"\n' "$name" "$host"
  printf '      traefik.http.routers.%s.entrypoints: "web,websecure"\n' "$name"
  printf '      traefik.http.routers.%s.tls: "true"\n' "$name"
  printf '      traefik.http.routers.%s.tls.certresolver: "%s"\n' "$name" "$ACME_RESOLVER"
  printf '      traefik.http.routers.%s.priority: "10"\n' "$name"
  printf '      traefik.http.routers.%s.service: "grindctrl-demos"\n' "$name"
done
